-- Добавляем колонки для внешнего вида
ALTER TABLE pets ADD COLUMN IF NOT EXISTS color VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS fur VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS ears VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS tail VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS size VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS special_marks TEXT;

-- Добавляем колонки для идентификации
ALTER TABLE pets ADD COLUMN IF NOT EXISTS marking_date DATE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS tag_number VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS brand_number VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS chip_number VARCHAR(50);
